In [3]:
#installing numpy
#! pip3 install numpy
import numpy as np
    

In [15]:
l=[[ 1., 0., 0.],
   [ 0., 1., 2.]]#python list
print(l,type(l))


print("")
k=np.array(l)#numpy array
print(k,type(k))

print("")
#reshape
l=[1,2,3,4,5,6,7,8,9]
z=np.array(l).reshape(3,3)
print(z)

[[1.0, 0.0, 0.0], [0.0, 1.0, 2.0]] <class 'list'>

[[1. 0. 0.]
 [0. 1. 2.]] <class 'numpy.ndarray'>

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
l=[1,2,3,4,5,6,7,8,9]
z=np.array(l).reshape(3,3)
print(z)
print(z.ndim)
print(z.size)
print(z.shape)
print(z.dtype.name)
print(z.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
9
(3, 3)
int64


In [24]:
#type specific array
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [26]:
#Zeros and ones with a specified dimention
print(np.zeros( (3,4) ))

print("\n")
np.ones( (2,3,4), dtype=np.int16 )

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]




array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [30]:
#get a array with elements between a specified  range and over specified interval 
np.arange(10,30,6)

array([10, 16, 22, 28])

In [32]:
#pi in numpy
np.pi

3.141592653589793

In [40]:
#functions 
print(np.sin(np.pi/2))
np.log(10)

1.0


2.302585092994046

In [41]:
#null value
np.nan

nan

In [ ]:
#basic airthmatic operaation


In [43]:
p=np.array([[0,0,0],
            [255,0,0],
            [0,255,0],
            [0,0,255],
            [255,255,255]])
c=np.array([[0,1,1,1,1,0],
            [0,1,0,0,0,0],
            [0,1,0,0,0,0],
            [0,1,0,0,0,0],
            [0,1,1,1,1,0]])
k=p[c]
k

array([[[  0,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [255,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [255,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [255,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        [  0,   0,   0]]])